
PROJECTS = "Projects"
ID = "id"
APP_ID = "app-id"
JOB_ID = "job-id"
GIT_URL = "git-url"
GIT_PATH = "git-path"
GIT_BRANCH = "git-branch"
TARGET_FILE = "target-file"
PREBUILD_SCRIPT = "prebuild-script"
PREBUILD_CONTEXT = "prebuild-context"
BUILD_CONTEXT = "build-context"
DESIRED_TAG = "desired-tag"
NOTIFY_EMAIL = "notify-email"
DEPENDS_ON = "depends-on"
