---
- name: Install latest docker and docker py
  yum: name={{item}} state=latest
  with_items:
    - docker
    - python-docker-py

- name: Enable Docker registry
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#?\s*ADD_REGISTRY=.*"
    replace='ADD_REGISTRY="--add-registry {{ public_registry }}:5000 --add-registry registry.centos.org"'

- name: Restart Docker
  service: name=docker state=restarted enabled=yes

#Push ca cert to slave for worker
- name: Ensure /opt/cccp-service/beanstalk_worker dir exists on Jenkins slaves
  file: dest=/opt/cccp-service/beanstalk_worker state=directory

- name: Push oc files to Jenkins slaves
  synchronize:
    mode: push
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
    rsync_opts:
        - "{{ rsync_ssh_opts }}"
  with_items:
    - {src: /tmp/oc, dest: /opt/cccp-service/oc}
    - {src: /tmp/oc_ca.crt, dest: /opt/cccp-service/ca.crt}
    - {src: /tmp/oc_node.kubeconfig, dest: /opt/cccp-service/node.kubeconfig}

- name: Get OpenShift server ip
  shell: echo `ping {{ groups['openshift'][0] }} -c 1 | awk '{print $3}'|head -n 1|sed 's/(//'|sed 's/)//'`
  register: openshift_server_ip_out

- debug: var=openshift_server_ip.stdout

- set_fact:
    openshift_server_ip: "{{ openshift_server_ip_out.stdout }}"

- name: Update settings
  template: src=settings.py.j2 dest=/opt/cccp-service/container_pipeline/lib/settings.py

- name: Build container-pipeline image
  shell: docker build -t container-pipeline -f ./Dockerfile .
  args:
      chdir: /opt/cccp-service

- name: Ensure log path exists
  file: path=/srv/pipeline-logs/cccp.log state=touch

- name: Start dispatcher worker
  docker:
      name: dispatcher-worker
      state: restarted
      image: container-pipeline
      command: /src/container_pipeline/workers/dispatcher.py
      restart_policy: always
      volumes:
        /srv/pipeline-logs:/srv/pipeline-logs:rw

- name: Start build worker
  docker:
      name: build-worker
      state: restarted
      image: container-pipeline
      command: /src/container_pipeline/workers/build.py
      restart_policy: always
      volumes:
        /srv/pipeline-logs:/srv/pipeline-logs:rw

- name: Start delivery worker
  docker:
      name: delivery-worker
      state: restarted
      command: /src/container_pipeline/workers/delivery.py
      image: container-pipeline
      restart_policy: always
      volumes:
        /srv/pipeline-logs:/srv/pipeline-logs:rw

- name: Pull Linter image
  docker_image:
      name: registry.centos.org/pipeline-images/dockerfile-lint
      state: present
      force: yes

- name: Copy Dockerfile linter worker
  copy:
      src: ../../scripts/cccp-dockerfile-lint-worker.service
      dest: /etc/systemd/system/cccp-dockerfile-lint-worker.service

- name: Enable and start Dockerfile linter worker
  service: name=cccp-dockerfile-lint-worker enabled=yes state=restarted
