---
- name: Install Atomic
  yum: name=atomic state=present
  sudo: yes
  tags: scanner

# Fix for issue:  https://github.com/projectatomic/atomic/issues/804
- name: Install python-dateutil
  yum: name=python-dateutil state=present
  sudo: yes
  tags: scanner

# Patch from https://github.com/projectatomic/atomic/commit/a261270e727353899675a3fde8f9108376bb27cf
- name: Patch atomic scanner to run on non tty input
  replace: >
      dest=/usr/lib/python2.7/site-packages/Atomic/scan.py
      regexp="'-it'"
      replace="'-t'"
  sudo: yes
  tags: scanner

- name: Install docker
  yum: name=docker state=present
  sudo: yes
  tags: scanner

- name: Start and Enable docker
  service: name=docker enabled=yes state=started
  sudo: yes
  tags: scanner

- name: Enable Docker Host socket
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#*\s*OPTIONS=.*"
    replace='OPTIONS="--selinux-enabled --log-driver=journald -H tcp://0.0.0.0:4243 -H unix:///var/run/docker.sock"'
  tags: scanner

- name: Enable Docker Registry
  replace: >
    dest=/etc/sysconfig/docker
    regexp="^#*\s*ADD_REGISTRY=.*"
    replace='ADD_REGISTRY="--insecure-registry {{ intranet_registry }} --add-registry {{ public_registry }} --add-registry registry.centos.org"'
  tags: scanner

- name: Set SELinux to permissive
  selinux:
      policy: targeted
      state: permissive
  tags: scanner

- name: Restart Docker
  service: name=docker state=restarted enabled=yes
  tags: scanner

- name: Install pipeline-scanner container
  docker_container:
      image: registry.centos.org/pipeline-images/pipeline-scanner:latest
      name: pipeline-scanner
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started
      pull: yes
  tags: scanner

- name: Install scanner-rpm-verify container
  docker_container:
      image: registry.centos.org/pipeline-images/scanner-rpm-verify:latest
      name: rpm-verify
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started
      pull: yes
  tags: scanner

- name: Install misc-package-updates container
  docker_container:
      image: registry.centos.org/pipeline-images/misc-package-updates:latest
      name: misc-package-updates
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started
      pull: yes
  tags: scanner


- name: Install misc-package-updates container
  docker_container:
      image: registry.centos.org/pipeline-images/container-capabilities-scanner:latest
      name: misc-package-updates
      privileged: true
      volumes:
        - /etc/atomic.d/:/host/etc/atomic.d/
      command: sh /install.sh
      state: started

- name: Get service files for workers
  copy:
    src: "{{ item.src }}"
    dest: "{{ item.dest }}"
  with_items:
      - {src: "../scripts/cccp-scan-worker.service", dest: /etc/systemd/system/cccp-scan-worker.service}
  tags: scanner

- name: Ensure log path exists
  file: path=/srv/pipeline-logs/cccp.log state=touch
  tags: scanner

- name: Enable Scanner worker
  service: name="cccp-scan-worker" state=restarted enabled=yes
  tags: scanner

- name: Enable Scanner worker
  service: name="cccp-scan-worker" state=restarted enabled=yes
  tags: scanner
